// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package eventmock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/rollify/rollify/internal/model"
)

// Subscriber is an autogenerated mock type for the Subscriber type
type Subscriber struct {
	mock.Mock
}

// SubscribeDiceRollCreated provides a mock function with given fields: subscribeID, roomID, h
func (_m *Subscriber) SubscribeDiceRollCreated(subscribeID string, roomID string, h func(context.Context, model.EventDiceRollCreated) error) error {
	ret := _m.Called(subscribeID, roomID, h)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, func(context.Context, model.EventDiceRollCreated) error) error); ok {
		r0 = rf(subscribeID, roomID, h)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnsubscribeDiceRollCreated provides a mock function with given fields: subscribeID, roomID
func (_m *Subscriber) UnsubscribeDiceRollCreated(subscribeID string, roomID string) error {
	ret := _m.Called(subscribeID, roomID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(subscribeID, roomID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
