// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package eventmock

import (
	model "github.com/rollify/rollify/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Subscriber is an autogenerated mock type for the Subscriber type
type Subscriber struct {
	mock.Mock
}

// RecvDiceRollCreated provides a mock function with given fields: roomID, h
func (_m *Subscriber) RecvDiceRollCreated(roomID string, h func(model.DiceRoll) error) {
	_m.Called(roomID, h)
}
