// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package eventmock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/rollify/rollify/internal/model"
)

// Subscriber is an autogenerated mock type for the Subscriber type
type Subscriber struct {
	mock.Mock
}

// SubscribeDiceRollCreated provides a mock function with given fields: roomID, userID, h
func (_m *Subscriber) SubscribeDiceRollCreated(roomID string, userID string, h func(context.Context, model.DiceRoll) error) error {
	ret := _m.Called(roomID, userID, h)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, func(context.Context, model.DiceRoll) error) error); ok {
		r0 = rf(roomID, userID, h)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnsubscribeDiceRollCreated provides a mock function with given fields: roomID, userID
func (_m *Subscriber) UnsubscribeDiceRollCreated(roomID string, userID string) error {
	ret := _m.Called(roomID, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(roomID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
