// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package usermock

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// ServiceMetricsRecorder is an autogenerated mock type for the ServiceMetricsRecorder type
type ServiceMetricsRecorder struct {
	mock.Mock
}

// MeasureUserServiceOpDuration provides a mock function with given fields: ctx, op, success, t
func (_m *ServiceMetricsRecorder) MeasureUserServiceOpDuration(ctx context.Context, op string, success bool, t time.Duration) {
	_m.Called(ctx, op, success, t)
}
