// Code generated by mockery v2.33.1. DO NOT EDIT.

package storagemock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// DiceRollRepositoryMetricsRecorder is an autogenerated mock type for the DiceRollRepositoryMetricsRecorder type
type DiceRollRepositoryMetricsRecorder struct {
	mock.Mock
}

// MeasureDiceRollRepoOpDuration provides a mock function with given fields: ctx, storageType, op, success, t
func (_m *DiceRollRepositoryMetricsRecorder) MeasureDiceRollRepoOpDuration(ctx context.Context, storageType string, op string, success bool, t time.Duration) {
	_m.Called(ctx, storageType, op, success, t)
}

// NewDiceRollRepositoryMetricsRecorder creates a new instance of DiceRollRepositoryMetricsRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDiceRollRepositoryMetricsRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *DiceRollRepositoryMetricsRecorder {
	mock := &DiceRollRepositoryMetricsRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
