// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package storagemock

import (
	context "context"

	model "github.com/rollify/rollify/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// DiceRollRepository is an autogenerated mock type for the DiceRollRepository type
type DiceRollRepository struct {
	mock.Mock
}

// CreateDiceRoll provides a mock function with given fields: ctx, roomID, userID, dr
func (_m *DiceRollRepository) CreateDiceRoll(ctx context.Context, roomID string, userID string, dr model.DiceRoll) error {
	ret := _m.Called(ctx, roomID, userID, dr)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, model.DiceRoll) error); ok {
		r0 = rf(ctx, roomID, userID, dr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
