// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package storagemock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// DiceRollRepositoryMetricsRecorder is an autogenerated mock type for the DiceRollRepositoryMetricsRecorder type
type DiceRollRepositoryMetricsRecorder struct {
	mock.Mock
}

// MeasureDiceRollRepoOpDuration provides a mock function with given fields: ctx, storageType, op, success, t
func (_m *DiceRollRepositoryMetricsRecorder) MeasureDiceRollRepoOpDuration(ctx context.Context, storageType string, op string, success bool, t time.Duration) {
	_m.Called(ctx, storageType, op, success, t)
}
