// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package storagemock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// RoomRepositoryMetricsRecorder is an autogenerated mock type for the RoomRepositoryMetricsRecorder type
type RoomRepositoryMetricsRecorder struct {
	mock.Mock
}

// MeasureRoomRepoOpDuration provides a mock function with given fields: ctx, storageType, op, success, t
func (_m *RoomRepositoryMetricsRecorder) MeasureRoomRepoOpDuration(ctx context.Context, storageType string, op string, success bool, t time.Duration) {
	_m.Called(ctx, storageType, op, success, t)
}
