// Code generated by mockery v2.33.1. DO NOT EDIT.

package storagemock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// RoomRepositoryMetricsRecorder is an autogenerated mock type for the RoomRepositoryMetricsRecorder type
type RoomRepositoryMetricsRecorder struct {
	mock.Mock
}

// MeasureRoomRepoOpDuration provides a mock function with given fields: ctx, storageType, op, success, t
func (_m *RoomRepositoryMetricsRecorder) MeasureRoomRepoOpDuration(ctx context.Context, storageType string, op string, success bool, t time.Duration) {
	_m.Called(ctx, storageType, op, success, t)
}

// NewRoomRepositoryMetricsRecorder creates a new instance of RoomRepositoryMetricsRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoomRepositoryMetricsRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoomRepositoryMetricsRecorder {
	mock := &RoomRepositoryMetricsRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
