// Code generated by mockery v2.33.1. DO NOT EDIT.

package storagemock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// UserRepositoryMetricsRecorder is an autogenerated mock type for the UserRepositoryMetricsRecorder type
type UserRepositoryMetricsRecorder struct {
	mock.Mock
}

// MeasureUserRepoOpDuration provides a mock function with given fields: ctx, storageType, op, success, t
func (_m *UserRepositoryMetricsRecorder) MeasureUserRepoOpDuration(ctx context.Context, storageType string, op string, success bool, t time.Duration) {
	_m.Called(ctx, storageType, op, success, t)
}

// NewUserRepositoryMetricsRecorder creates a new instance of UserRepositoryMetricsRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepositoryMetricsRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepositoryMetricsRecorder {
	mock := &UserRepositoryMetricsRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
