// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package storagemock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// UserRepositoryMetricsRecorder is an autogenerated mock type for the UserRepositoryMetricsRecorder type
type UserRepositoryMetricsRecorder struct {
	mock.Mock
}

// MeasureUserRepoOpDuration provides a mock function with given fields: ctx, storageType, op, success, t
func (_m *UserRepositoryMetricsRecorder) MeasureUserRepoOpDuration(ctx context.Context, storageType string, op string, success bool, t time.Duration) {
	_m.Called(ctx, storageType, op, success, t)
}
