// Code generated by mockery v2.33.1. DO NOT EDIT.

package roommock

import (
	context "context"

	room "github.com/rollify/rollify/internal/room"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateRoom provides a mock function with given fields: ctx, r
func (_m *Service) CreateRoom(ctx context.Context, r room.CreateRoomRequest) (*room.CreateRoomResponse, error) {
	ret := _m.Called(ctx, r)

	var r0 *room.CreateRoomResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, room.CreateRoomRequest) (*room.CreateRoomResponse, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, room.CreateRoomRequest) *room.CreateRoomResponse); ok {
		r0 = rf(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*room.CreateRoomResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, room.CreateRoomRequest) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoom provides a mock function with given fields: ctx, r
func (_m *Service) GetRoom(ctx context.Context, r room.GetRoomRequest) (*room.GetRoomResponse, error) {
	ret := _m.Called(ctx, r)

	var r0 *room.GetRoomResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, room.GetRoomRequest) (*room.GetRoomResponse, error)); ok {
		return rf(ctx, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, room.GetRoomRequest) *room.GetRoomResponse); ok {
		r0 = rf(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*room.GetRoomResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, room.GetRoomRequest) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
