// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package roommock

import (
	context "context"

	room "github.com/rollify/rollify/internal/room"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CreateRoom provides a mock function with given fields: ctx, r
func (_m *Service) CreateRoom(ctx context.Context, r room.CreateRoomRequest) (*room.CreateRoomResponse, error) {
	ret := _m.Called(ctx, r)

	var r0 *room.CreateRoomResponse
	if rf, ok := ret.Get(0).(func(context.Context, room.CreateRoomRequest) *room.CreateRoomResponse); ok {
		r0 = rf(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*room.CreateRoomResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, room.CreateRoomRequest) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
