// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package roommock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ServiceMetricsRecorder is an autogenerated mock type for the ServiceMetricsRecorder type
type ServiceMetricsRecorder struct {
	mock.Mock
}

// MeasureRoomServiceOpDuration provides a mock function with given fields: ctx, op, success, t
func (_m *ServiceMetricsRecorder) MeasureRoomServiceOpDuration(ctx context.Context, op string, success bool, t time.Duration) {
	_m.Called(ctx, op, success, t)
}
