// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package dicemock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/rollify/rollify/internal/model"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateDiceRoll provides a mock function with given fields: ctx, r
func (_m *Repository) CreateDiceRoll(ctx context.Context, r model.DiceRoll) error {
	ret := _m.Called(ctx, r)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.DiceRoll) error); ok {
		r0 = rf(ctx, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
