// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package dicemock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/rollify/rollify/internal/model"
)

// RollerMetricsRecorder is an autogenerated mock type for the RollerMetricsRecorder type
type RollerMetricsRecorder struct {
	mock.Mock
}

// MeasureDiceRollQuantity provides a mock function with given fields: ctx, rollerType, diceRoll
func (_m *RollerMetricsRecorder) MeasureDiceRollQuantity(ctx context.Context, rollerType string, diceRoll *model.DiceRoll) {
	_m.Called(ctx, rollerType, diceRoll)
}

// MeasureDieRollResult provides a mock function with given fields: ctx, rollerType, dieRoll
func (_m *RollerMetricsRecorder) MeasureDieRollResult(ctx context.Context, rollerType string, dieRoll *model.DieRoll) {
	_m.Called(ctx, rollerType, dieRoll)
}
