name: CI

on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    # Execute the checks inside the container instead the VM.
    container: golangci/golangci-lint:v1.27.0-alpine
    steps:
      - uses: actions/checkout@v1
      - run: ./scripts/check/check.sh

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2-beta
        with:
          go-version: 1.14
      - run: make ci-test
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_UPLOAD_TOKEN }}
          file: ./.test_coverage.txt

  release-image:
    if: startsWith(github.ref, 'refs/tags/')
    env:
      TAG_IMAGE_LATEST: "true"
      PROD_IMAGE_NAME: ${GITHUB_REPOSITORY}
    needs: [check, test]
    name: Release image
    runs-on: ubuntu-latest
    # Only run in master and when has a tag.
    steps:
      - name: Set tag on VERSION env var
        run: echo ::set-env name=VERSION::$(echo ${GITHUB_REF:10})
      - uses: actions/checkout@v1
      - name: Build image
        run: make build-image
      - name: Docker login
        run: docker login ${DOCKER_HOST} -u ${DOCKER_USER} -p ${DOCKER_TOKEN}
        env:
          # DockerHub.
          DOCKER_HOST: ""
          DOCKER_USER: slok
          DOCKER_TOKEN: ${{secrets.DOCKER_HUB_TOKEN}}
      - name: Publish image
        run: make publish-image
